#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";
require_once __DIR__ . "/app/core/Helpers/helpers.php";

use Imissher\Equinox\app\core\Application;

$config = [
    'db' => [
        'driver' => env('DB_DRIVER'),
        'dsn' => "host=" . env('DB_HOST') . ";port=" . env('DB_PORT') . ";dbname=" . env('DB_NAME'),
        'user' => env('DB_USERNAME'),
        'password' => env('DB_PASSWORD')
    ],
    'master' => $argv,
    'display_error' => env('DISPLAY_ERROR'),
    'app_version' => env('APP_VERSION')
];

$app = new Application(__DIR__, $config);
