name: PHP Composer Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Composer
      uses: php-actions/composer@v6

    - name: Run test suite
      run: ./vendor/bin/phpunit tests
